# Generated by Django 4.2.1 on 2023-05-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_hora_extra', '0003_registrohoraextra_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrohoraextra',
            name='motivo',
            field=models.CharField(max_length=100),
        ),
    ]
