# Generated by Django 4.2 on 2023-04-26 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da empresa'),
        ),
    ]
