# Generated by Django 4.2.1 on 2023-05-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0004_departamentos_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamentos',
            name='user',
        ),
    ]
